### ISSUE TITLE
Output Problem

### ISSUE THREAD

**Issue by OpusXI** [gugarosa/viviner#2]
Hi,

May i ask how do i use the script? I copied the code on to command line and added vivino.json as my argument. It doesn't output anything and only prints "number of matches: 5".

Is it possible that I am not using it correctly?

**Comment by gugarosa** [comment]
Hello @OpusXI! I Hope everything is going well with you.

I am sorry about that. There was indeed a bug when the "number of matches" was inferior to a pre-defined constant. Could you please update your repository with the latest changes and try again?

It should work now.

Thank you and best regards,
Gustavo.

**Comment by OpusXI** [comment]
Hello @gugarosa 

I updated the repo, and it works perfectly. Thank you so much.

Best regards,
OpusXI
