### ISSUE TITLE
Not all results

### ISSUE THREAD

**Issue by ddb9797** [gugarosa/viviner#3]
Hi, if I run the script I only get 8 results. If I look at the vivino website with the same parameters I also only get 8 results. Did the API change? If so, can you upload the whole database (not only brazilian wines)?

Sincerely,

**Comment by gugarosa** [comment]
Hello @ddb9797! I hope everything is going well with you.

I just run the default script and got 700 results. I don't think the API has changed.

Best regards,
Gustavo.

**Comment by ddb9797** [comment]
I found out what the problem was. When I was connected to a Brazilian VPN I had 700 results, but any other country you only get a few results

**Comment by gugarosa** [comment]
Thanks for that information! I didn't know their API returned results based on geo-localization.
